services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loopin-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: npm run start:dev

  postgres:
    image: postgres:16
    container_name: loopin-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: loopin
      POSTGRES_PASSWORD: loopin123
      POSTGRES_DB: loopin_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
